version: "3.8"

services:    
  app:
    container_name: app_real_estate
    build:
      context: .
      args:
        - INSTALL_DEV=true
      dockerfile: Dockerfile
    volumes:
      - ./:/home/site/wwwroot
    command: uvicorn real_estate_adviser_service.main:app --host 0.0.0.0 --port 8000 --reload
    # environment:
    #   DB_HOST: mssql_server
    #   DB_USERNAME: ${DB_USERNAME}
    #   DB_PASSWORD: ${DB_PASSWORD}
    #   DB_PORT: ${DB_PORT}
    #   DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
